/**
 * @author <Your Name> <Your e-mail/Website if you would like>
 * @license [MIT](http://www.opensource.org/licenses/mit-license.php)
 */
(function ($) {
	'use strict';

	$.sceditor.locale["cn"] = {
		"Bold": "粗体",
		"Italic": "斜体",
		"Underline": "下划线",
		"Strikethrough": "删除线",
		"Subscript": "下标",
		"Superscript": "上标",
		"Align left": "靠左对齐",
		"Center": "置中",
		"Align right": "靠右对齐",
		"Justify": "两端对齐",
		"Font Name": "字体",
		"Font Size": "字号",
		"Font Color": "字色",
		"Remove Formatting": "格式清除",
		"Cut": "剪切",
		"Your browser does not allow the cut command. Please use the keyboard shortcut Ctrl/Cmd-X": "您的浏览器不支持剪切命令，请使用快捷键 Ctrl/Cmd-X",
		"Copy": "拷贝",
		"Your browser does not allow the copy command. Please use the keyboard shortcut Ctrl/Cmd-C": "您的浏览器不支持拷贝命令，请使用快捷键 Ctrl/Cmd-C",
		"Paste": "粘贴",
		"Your browser does not allow the paste command. Please use the keyboard shortcut Ctrl/Cmd-V": "您的浏览器不支持粘贴命令，请使用快捷键 Ctrl/Cmd-V",
		"Paste your text inside the following box:": "请在下面贴入您的文本",
		"Paste Text": "粘贴纯文本",
		"Bullet list": "符号列表",
		"Numbered list": "编号列表",
		"Undo": "恢复",
		"Redo": "撤消",
		"Rows:": "行数",
		"Cols:": "列数",
		"Insert a table": "插入表格",
		"Insert a horizontal rule": "插入分隔符",
		"Code": "代码",
		"Width (optional):": "宽度(选填)",
		"Height (optional):": "高度(选填)",
		"Insert an image": "插入图片",
		"E-mail:": "Email地址",
		"Insert an email": "插入Email地址",
		"URL:": "网址",
		"Insert a link": "插入链接",
		"Unlink": "取消链接",
		"More": "更多",
		"Insert an emoticon": "插入表情符号",
		"Video URL:": "视频地址",
		"Insert": "插入",
		"Insert a YouTube video": "插入YouTube视频",
		"Insert current date": "插入当前日期",
		"Insert current time": "插入当前时间",
		"Print": "打印",
		"View source": "查看代码",
		"Description (optional):": "描述(选填)",
		"Enter the image URL:": "输入图片地址",
		"Enter the e-mail address:": "输入email地址",
		"Enter the displayed text:": "输入显示文字",
		"Enter URL:": "输入网址",
		"Enter the YouTube video URL or ID:": "输入YouTube地址或编号",
		"Insert a Quote":"插入引用",
		"Invalid YouTube video": "无效的YouTube视频",

		dateFormat: "year-month-day"
	};
})(jQuery);

function initEditor(id){
    $("#"+id).sceditor({
        locale:'cn',
        resizeEnabled:false,
        toolbar: "bold,italic,underline|strike,subscript,superscript|left,center,right,justify|font,size,color,removeformat|bulletlist,orderedlist,table,horizontalrule,image,email|" +
            "link,unlink|emoticon,date,time",
        style: "plugin/sceditor/jquery.sceditor.default.min.css",
        emoticonsEnabled:true,
        emoticons:{
            dropdown: {
                "拽":"plugin/smiley/smiley-0.gif",
                "流汗":"plugin/smiley/smiley-1.gif",
                "嘘":"plugin/smiley/smiley-2.gif",
                "不高兴":"plugin/smiley/smiley-3.gif",
                "汗颜":"plugin/smiley/smiley-4.gif",
                "惊悚":"plugin/smiley/smiley-5.gif",
                "调皮":"plugin/smiley/smiley-6.gif",
                "担心":"plugin/smiley/smiley-7.gif",
                "酷":"plugin/smiley/smiley-8.gif",
                "亲亲":"plugin/smiley/smiley-9.gif",
                "瞌睡":"plugin/smiley/smiley-10.gif",
                "坏笑":"plugin/smiley/smiley-11.gif",
                "左哼哼":"plugin/smiley/smiley-12.gif",
                "害羞":"plugin/smiley/smiley-13.gif",
                "微笑":"plugin/smiley/smiley-14.gif",
                "猪":"plugin/smiley/smiley-15.gif",
                "委屈":"plugin/smiley/smiley-16.gif",
                "色":"plugin/smiley/smiley-17.gif",
                "火大":"plugin/smiley/smiley-18.gif",
                "快哭了":"plugin/smiley/smiley-19.gif",
                "欠揍":"plugin/smiley/smiley-20.gif",
                "尴尬":"plugin/smiley/smiley-21.gif",
                "大哭":"plugin/smiley/smiley-22.gif",
                "哈欠":"plugin/smiley/smiley-23.gif",
                "惊讶":"plugin/smiley/smiley-24.gif",
                "吓":"plugin/smiley/smiley-25.gif",
                "咒骂":"plugin/smiley/smiley-26.gif",
                "白眼":"plugin/smiley/smiley-27.gif",
                "鼻涕":"plugin/smiley/smiley-28.gif",
                "可怜":"plugin/smiley/smiley-29.gif",
                "奋斗":"plugin/smiley/smiley-30.gif",
                "炫耀":"plugin/smiley/smiley-31.gif",
                "捂嘴":"plugin/smiley/smiley-32.gif",
                "扣鼻屎":"plugin/smiley/smiley-33.gif",
                "大笑":"plugin/smiley/smiley-34.gif",
                "囧":"plugin/smiley/smiley-35.gif",
                "鄙视":"plugin/smiley/smiley-36.gif",
                "皱眉":"plugin/smiley/smiley-37.gif",
                "晕":"plugin/smiley/smiley-38.gif",
                "鼓掌":"plugin/smiley/smiley-39.gif",
                "抓狂":"plugin/smiley/smiley-40.gif",
                "困":"plugin/smiley/smiley-41.gif",
                "哈哈":"plugin/smiley/smiley-42.gif",
                "相当鄙视":"plugin/smiley/smiley-43.gif",
                "奸笑":"plugin/smiley/smiley-44.gif",
                "右哼哼":"plugin/smiley/smiley-45.gif",
                "吐":"plugin/smiley/smiley-46.gif",
                "不好意思":"plugin/smiley/smiley-47.gif",
                "为什么":"plugin/smiley/smiley-48.gif",
                "眼泪":"plugin/smiley/smiley-49.gif",
                "可爱":"plugin/smiley/smiley-50.gif",
                "骷髅":"plugin/smiley/smiley-51.gif",
                "再见":"plugin/smiley/smiley-52.gif",
                "很棒":"plugin/smiley/smiley-53.gif",
                "衰":"plugin/smiley/smiley-54.gif",
                "闭嘴":"plugin/smiley/smiley-55.gif"
            }
        }
    });
}